# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a28df1c2d3401e3f12dae3c2ae662d3226e6b2685676f19e25c0989f3cccd8639902737ec3945c38a3dddb25259b60c1f5d888baf4d50e135faa66065b12bcb

test:
  secret_key_base: 9119ed7f8233a92947bd81bca135ed7c58fb57cd5cf3bae50018d0a3ec1f01fb8c6b58ed6e24242a8d9047cc3ea1bff7838b62e5e4682f647f59a1d6b5383085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
